In [1]:
#Vamos analisar os dado de vendas por regiões
import pandas as pd

In [4]:
dadosIniciais = pd.read_csv("Todos pedido.csv")

In [58]:
dadosIniciais

,Order ID,Package ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,...,Neighborhood,House Name or Number,City,State,Country,Zipcode,Shipping Information,Invoice Status,Buyer Message,Seller Note
0,582842497552581968,\t,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,São Paulo,SP,Brasil,********\t,C***** q***** q*****\n(+55)119******12\n******...,NaN,NaN,NaN
1,582842361247204456,1187749005812008040\t,Enviado,Entregue,NaN,Normal,1734385029151425910,21011-41,Chinelo Masculino Esportivo Casual Confortável,"Preto/cáqui, 41CH-39BR",...,Três Marias,casa,Porto Velho,RO,Brasil,76812565\t,Francisca Ribeiro\n(+55)699******98\nRua Bela ...,NF-e valid,NaN,NaN
2,582841805697353604,1187744398505052036\t,Enviado,Entregue,NaN,Normal,1734385029150967158,21009-40,Chinelo Masculino Esportivo Casual Confortável,"Cinza escuro/cinza claro, 40CH-38BR",...,bela vista,ao lado mercado do Barateiro,Santo Antônio,RN,Brasil,59255000\t,Eduardo Januário\n(+55)849******35\nLot. são d...,NF-e valid,NaN,NaN
3,582841574826018761,1187745633354155977\t,Concluído,Concluído,Return/Refund,Normal,1734385029151425910,21011-41,Chinelo Masculino Esportivo Casual Confortável,"Preto/cáqui, 41CH-39BR",...,Cruzeiro do Anil,Rua Brasília,São Luís,MA,Brasil,65060080\t,rhyan Pablo\n(+55)989******73\nRua Brasília 21...,NF-e valid,NaN,NaN
4,582840897842283785,\t,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,Belo Horizonte,MG,Brasil,********\t,s*******\n(+55)319******43\n*********** **** *...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6342,581733977956845009,1179801065910535633\t,Concluído,Concluído,NaN,Normal,1733632665784583542,ME-10-Cachorro-Rosa-35-40,Meia Infantil 3D Divertida Personagem Longa At...,Cachorro-Rosa-35-40,...,*********,*****,Florianópolis,SC,Brasil,********\t,A** R**** S**** M*******\n(+55)489******39\n**...,NF-e valid,NaN,NaN
6343,581733977956845009,1179801065910535633\t,Concluído,Concluído,NaN,Normal,1733632665784714614,ME-10-Unicornio-35-40,Meia Infantil 3D Divertida Personagem Longa At...,Unicornio-35-40,...,*********,*****,Florianópolis,SC,Brasil,********\t,A** R**** S**** M*******\n(+55)489******39\n**...,NF-e valid,NaN,NaN
6344,581719808557155502,1179698223893087406\t,Concluído,Concluído,NaN,Normal,1733488464333997430,SPT-MGC-Preta-Branca-Cinza-40-46,Kit 3 Pares Meia Sapatilha Invisível Masculina...,Preta-Branca-Cinza,...,***********************,***************************,Salvador,BA,Brasil,********\t,M*****\n(+55)719******46\n************* ** ***...,NF-e valid,NaN,NaN
6345,581671400374240652,1179351233822426508\t,Concluído,Concluído,NaN,Normal,1733488904810300790,SQ-EMCA-Chumbo-Cinza-Preta-40-46,Kit até 3 Pares de Meia feminina ou masculina ...,Chumbo-Cinza-Preta,...,******,***************,Lagoa Vermelha,RS,Brasil,********\t,G******** Z**\n(+55)549******28\n*************...,NF-e valid,NaN,NaN
6346,581592143668938589,1178790423390947165\t,Concluído,Concluído,NaN,Normal,1733487024796501366,QS-LM-M02-Branco-40-46,Harajuku Meias De Algodão Casal Mão De Sucção ...,Branco,...,*********************************,******************************,Tibagi,PR,Brasil,********\t,A**\n(+55)429******71\n***********************...,NF-e valid,NaN,NaN

In [59]:
#dadosIniciais[['Shipping Provider Name', 'Buyer Username', 'CPF Number', 'CPF Name',
#       'Recipient', 'Phone #', 'Street Name', 'Street Number', 'Neighborhood',
#       'House Name or Number', 'City', 'State', 'Country', 'Zipcode',
#       'Shipping Information', 'Invoice Status', 'Buyer Message']].head(4)

In [60]:
#dadosIniciais.shape

In [61]:
#dadosIniciais.info()

In [62]:
#dadosIniciais.isnull().sum()

In [63]:
#Preciso montar um banco de cadastro de todos os clientes que já comptraram na loja.
#Analisar as regiões de compras.
#Analiosar os valores adquiridos por cada região.
#Analisar a média de preço gasto por pedido.
#Analisar quais os produdos mais vendidos.
#Analisar quais os pedidos mais vendidos por região.
#Verificar por produto a receita que ele da de retorno - custo de produção/compra.
#Verificar o receita_venda - Custo_per_prouto - frete.
#Verificar a taxa de cancelamento por produto.

In [68]:
# Banco de dados de todos os clientes
dadosClientes_iniciais = pd.DataFrame(data = {"Nome Cliente":dadosIniciais["CPF Name"],"Cidade":dadosIniciais["City"],"Estado":dadosIniciais["State"],"País":dadosIniciais["Country"]} )
dadosDosClientes = dadosClientes_iniciais[dadosClientes_iniciais.duplicated(subset = ["Nome Cliente"], keep = 'first') == False]

In [65]:
dadosDosClientes

                             Nome Cliente          Cidade Estado    País
0                    CELINA QUISPE QUISPE       São Paulo     SP  Brasil
1            FRANCISCA CHAGAS DE OLIVEIRA     Porto Velho     RO  Brasil
2               EDUARDO JANUARIO DA COSTA   Santo Antônio     RN  Brasil
3              RHYAN PABLO DE JESUS SERRA        São Luís     MA  Brasil
4                ANA PAULA DE SOUZA GOMES  Belo Horizonte     MG  Brasil
...                                   ...             ...    ...     ...
6341       SUELEN CRISTINA DE PAULA SOUZA        Salvador     BA  Brasil
6342             ANA RAINA SILVA MONTEIRO   Florianópolis     SC  Brasil
6344           DANIEL JOCTA LINS DE PAULA        Salvador     BA  Brasil
6345                        GUILHERME ZIR  Lagoa Vermelha     RS  Brasil
6346  ADELIA APARECIDA MARTINS DE FREITAS          Tibagi     PR  Brasil

[5084 rows x 4 columns]

In [67]:
dados_cancelado = dadosIniciais[dadosIniciais["Order Status"] == "Cancelado"]

,Order ID,Package ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,...,Neighborhood,House Name or Number,City,State,Country,Zipcode,Shipping Information,Invoice Status,Buyer Message,Seller Note
0,582842497552581968,\t,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,São Paulo,SP,Brasil,********\t,C***** q***** q*****\n(+55)119******12\n******...,NaN,NaN,NaN
4,582840897842283785,\t,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,Belo Horizonte,MG,Brasil,********\t,s*******\n(+55)319******43\n*********** **** *...,NaN,NaN,NaN
7,582840426520282538,\t,Cancelado,Cancelado,Cancel,Normal,1733632665784518006,ME-10-Cachorro- Caramelo-35-40,Meia Maluca Infantil - Adulto 3D Divertida Per...,Cachorro- Caramelo-35-40,...,*********************,****,Paiçandu,PR,Brasil,********\t,R******** A*\n(+55)449******18\n**************...,NaN,NaN,NaN
16,582838521953289344,\t,Cancelado,Cancelado,Cancel,Normal,1733831958082979190,HM-BAF-Preto-35-41,Meia para Pilates Antiderrapante Profissional ...,"Preto, 1 Pares",...,************,****,Itaquaquecetuba,SP,Brasil,********\t,C***\n(+55)119******46\n**********************...,NaN,NaN,NaN
21,582837813804565800,\t,Cancelado,Cancelado,Cancel,Normal,1734385029151556982,21011-43,Chinelo Masculino Esportivo Casual Confortável,"Preto/cáqui, 43CH-41BR",...,*******,*******,Itaocara,RJ,Brasil,********\t,K***** B****\n(+55)229******90\n**************...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6311,582012927836455999,1181771397629903935\t,Cancelado,Cancelado,Cancel,Normal,1733488904810300790,SQ-EMCA-Chumbo-Cinza-Preta-40-46,Kit até 3 Pares de Meia feminina ou masculina ...,Chumbo-Cinza-Preta,...,*****************,*****************,Birigui,SP,Brasil,********\t,m***\n(+55)189******95\n***************** ****...,NF-e valid,NaN,NaN
6320,581992674555758303,1181638733525518047\t,Cancelado,Cancelado,Cancel,NaN,1733487024796501366,QS-LM-M02-Branco-40-46,Harajuku Meias De Algodão Casal Mão De Sucção ...,Branco,...,****************,*****************,Goiânia,GO,Brasil,********\t,T*** P****** P******\n(+55)629******73\n******...,NaN,NaN,NaN
6328,581807787087922940,1180325540748035836\t,Cancelado,Cancelado,Cancel,Normal,1733606302749590902,21079-39-40,Sandalia Babuche unissex Leve e Confortavel Ad...,"Preto, 40 BR",...,*******************,********************,Imperatriz,MA,Brasil,********\t,J***** L***\n(+55)999******00\n************ **...,NaN,NaN,NaN
6329,581807787087922940,1180325540748035836\t,Cancelado,Cancelado,Cancel,Normal,1733487024796501366,QS-LM-M02-Branco-40-46,Harajuku Meias De Algodão Casal Mão De Sucção ...,Branco,...,*******************,********************,Imperatriz,MA,Brasil,********\t,J***** L***\n(+55)999******00\n************ **...,NaN,NaN,NaN
6339,581770471157630267,1180058480278537531\t,Cancelado,Cancelado,Cancel,NaN,1733645607653639542,QS-LM-M02-Preto-Branco-40-46,Harajuku Meias De Algodão Casal Mão De Sucção ...,Preto+Branco,...,********************,****************,Guarulhos,SP,Brasil,********\t,P******* M****** d* C****\n(+55)119******07\n*...,NaN,NaN,NaN